name: 'Lock Closed Issues'

on:
  schedule:
    # This runs the bot automatically every day at midnight
    - cron: '0 0 * * *'

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5
        with:
          # Number of days of inactivity before a closed issue is locked
          issue-inactive-days: '30'
          
          # The polite message the bot will leave before locking
          issue-comment: >
            This thread has been automatically locked since there has not been
            any recent activity after it was closed. Please open a new issue for
            related bugs and link to this thread if helpful.
